# Generated by Django 3.1.7 on 2021-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('brand_name', models.CharField(db_column='brand_Name', max_length=45, primary_key=True, serialize=False)),
                ('brand_ment', models.CharField(db_column='brand_Ment', max_length=200)),
                ('brand_genre', models.CharField(db_column='brand_Genre', max_length=45)),
                ('design_point', models.CharField(db_column='design_Point', max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'global',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('brand_name', models.CharField(db_column='brand_Name', max_length=45, primary_key=True, serialize=False)),
                ('brand_ment', models.CharField(db_column='brand_Ment', max_length=200)),
                ('brand_genre', models.CharField(db_column='brand_Genre', max_length=45)),
                ('design_point', models.CharField(db_column='design_Point', max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'middle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='National',
            fields=[
                ('brand_name', models.CharField(db_column='brand_Name', max_length=45, primary_key=True, serialize=False)),
                ('brand_ment', models.CharField(db_column='brand_Ment', max_length=200)),
                ('brand_genre', models.CharField(db_column='brand_Genre', max_length=45)),
                ('design_point', models.CharField(db_column='design_Point', max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'national',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soho',
            fields=[
                ('brand_name', models.CharField(db_column='brand_Name', max_length=45, primary_key=True, serialize=False)),
                ('brand_ment', models.CharField(db_column='brand_Ment', max_length=200)),
                ('brand_genre', models.CharField(db_column='brand_Genre', max_length=45)),
                ('design_point', models.CharField(db_column='design_Point', max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'soho',
                'managed': False,
            },
        ),
    ]
