# Generated by Django 3.1.7 on 2021-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urtype_main_survey', '0002_auto_20210327_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
                ('user_age', models.IntegerField(db_column='user_Age')),
                ('user_job', models.CharField(db_column='user_Job', max_length=50)),
                ('brand_name', models.CharField(db_column='brand_Name', max_length=50)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='globals',
            table='globals',
        ),
    ]
